### ISSUE TITLE
Closed ports

### ISSUE THREAD

**Issue by andriypartyshev** [TechmanRobotInc/tmr_ros1#5]
This is not so much an issue with the driver as with the ports on the tm5-900 controller. After having an issue where no connection was established i ran an _nmap -Pn robot-ip_ and it returned a list of open ports (as i understood it) and none of them were 5890 or 5891 (or 502 for that matter (Modbus slave)) 
Is there a quick and easy fix for this issue?
Am i missing something that is not in the manual or is it a robot controller factory setup issue?

**Comment by karl-exwzd** [comment]
I have the same issue and would very much like some advice on how to proceed.

The ports are reported to be closed by `nmap -Pn <robot_ip>` as @Medievalpunk said, yet in the TMflow terminal it is clearly written "Listen opens on 127.0.0.1:5890" and "Ethernet Slave opens on 127.0.0.1:5891" when the program is started.

Perhaps it should listen to 0.0.0.0 instead of 127.0.0.1, but I have no idea on where to set that setting...

**Comment by jvdtoorn** [comment]
@exwzd-kk I had the same problem. For me the problem was that I plugged the ethernet cable into the wrong port on the TM machine. It should be connected to the port labelled with 'GigE'.

To verify if your problem is solved, the shown IP that TMFlow listens on should **not** be 127.0.0.1 (localhost). It should be a local IP on the network, e.g. 192.168.x.x.

**Comment by karl-exwzd** [comment]
@julespalles Thank you for your input. Unfortunately, my machine does not feature markings next to the Ethernet ports.

Previously, the robot worked well with the [deprecated driver](https://github.com/kentsai0319/techman_robot). It seems the control interface ports have changed and therefore the system does not behave as before. I suspect I should change the IP setting somewhere... but where is that setting? I went though all the imaginable menus in TMFlow, perhaps I should try other Ethernet ports and hope it works automagically.

**Comment by jvdtoorn** [comment]
@exwzd-kk see my other comment, you should update TMFlow to version 1.80

**Comment by jvdtoorn** [comment]
What is your output when running `scripts/test_conncection.py` from my [techmanpy](https://github.com/jvdtoorn/techmanpy) driver?

**Comment by karl-exwzd** [comment]
@julespalles I followed your suggestion and tested the other Ethernet ports on the robot, indeed that was the issue.

Now I see this in the logs: "Listen opens on 192.168.29.138:5890" and "Ethernet Slave opens on 192.168.29.138:5891".

I have TMFlow 1.80.5300.

**Comment by jvdtoorn** [comment]
@exwzd-kk great to hear that your problem is solved!

**Comment by carltech22** [comment]
Hello @TechmanRobotIncOwner and  @karl-exwzd ,
I am experiencing a similar issue issue here where I'm not able to connect to the TM5-900 Omron robot running TMFlow 1.84.2200 because the listening node opens on 127.0.0.1:5890. I have tried just about everything to talk to the robot. I followed the manuals and online documentation exactly and still nothing works. I have setup a static IP address for the robot i.e 169.254.255.186 and I have configured my network settings on my laptop to be on the same network 169.254.255.20 and same subnet mask. I tried to connect to the robot via Hercules TCP Client using the robot's static IP on the same port and the connection times out. The log message on TMFlow says the following
"0x0004F000 Listen opens on 127.0.0.1:5890

![Image](https://github.com/user-attachments/assets/da0097e0-4830-4d7a-ae13-4702e65c5ee7)
![Image](https://github.com/user-attachments/assets/ef8f6b0f-57cf-491d-85cc-5974fabb4be7)
